pub mod and_sensor_and_pool;
pub mod array_of_counters;
pub mod artifacts_pool;
pub mod compatible_with_iterator_sensor;
pub mod maximize_pool;
pub mod noop_sensor;
pub mod sum_coverage_pool;
pub mod unique_coverage_pool;
// pub mod unique_values_pool;
pub mod unit_pool;
pub use crate::code_coverage_sensor::CodeCoverageSensor;
pub mod most_n_diverse_pool;
