fuzzcheck_mutators_derive::make_basic_tuple_mutator!(2);
fuzzcheck_mutators_derive::make_basic_tuple_mutator!(3);
fuzzcheck_mutators_derive::make_basic_tuple_mutator!(4);
fuzzcheck_mutators_derive::make_basic_tuple_mutator!(5);
fuzzcheck_mutators_derive::make_basic_tuple_mutator!(6);
fuzzcheck_mutators_derive::make_basic_tuple_mutator!(7);
fuzzcheck_mutators_derive::make_basic_tuple_mutator!(8);
fuzzcheck_mutators_derive::make_basic_tuple_mutator!(9);
fuzzcheck_mutators_derive::make_basic_tuple_mutator!(10);
